"""Subscription model

Revision ID: fed6341867c5
Revises: a72f4baf9084
Create Date: 2020-05-22 22:22:23.666236

"""

# revision identifiers, used by Alembic.
revision = 'fed6341867c5'
down_revision = 'a72f4baf9084'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('subscription', sa.Unicode(length=1024), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=True))
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
